INSERT INTO session5(Sensor_nr) VALUES ('sd');
select * from session_0084 where Sensor_nr='2';
show tables;
SET SQL_SAFE_UPDATES = 1;
insert into new_table (idnew_table) values (500);
DROP DATABASE sensors; 
CREATE DATABASE sensors;
select * from sensor_sessions where session=122;
delete from sensors where Interface='Analog_digital' AND Sensor_id>=80 AND Sensor_id<=80;
select * from sensors ;
select * from i2c_sensors ;
select Read_addr from i2c_sensors where Sensor_id=2;
select * from analog_sensors ;
select * from i2c_sensors,sensors where i2c_sensors.Sensor_id=sensors.Sensor_id ;
select sensor_id from sensors;
select * from sensor_sessions ;
SELECT * FROM sensor_sessions ORDER BY id DESC LIMIT 1;
select Sensor_id,Name,Sensing_type from sensors where Interface='Analog_digital';
CREATE TABLE  session_10 (id INT(64) NOT NULL AUTO_INCREMENT,Sensor_nr VARCHAR(10),Date TIMESTAMP,Value INT(64),PRIMARY KEY(id));